// export const GET_RECIPES_BY_SEARCH_BAR = 'GET_RECIPES_BY_SEARCH_BAR';
export const GET_RECIPES_BY_CATEGORY = 'GET_RECIPES_BY_CATEGORY';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
