export const GET_RECIPES_BY_CATEGORY = 'GET_RECIPES_BY_CATEGORY';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_RECOMMENDED_RECIPES = 'GET_RECOMMENDED_RECIPES';
